routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',  [App\Http\Controllers\foto\FotoController::class, 'index'] );

Auth::routes();


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/perfilpublico{id_user}', [App\Http\Controllers\foto\FotoController::class, 'perfilpublico'])->name('perfilpublico');

Route::resource('foto', App\Http\Controllers\foto\FotoController::class);

Route::resource('categoria', App\Http\Controllers\categoria\CategoriaController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'nickname',
        'rol',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

   public function fotos()
   {
       return $this->hasMany('App\Models\foto', 'id_foto');
   } 
}

app/Models/categoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class categoria extends Model
{
    use HasFactory;
    protected $fillable = [
        
        'nombre_categoria',

    ];

    public function foto()
    {
        return $this->hasone('App\Models\foto');
    }

   
}

app/Models/foto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class foto extends Model
{
    use HasFactory;
    protected $fillable =[
            
       
        'descripcion',
        'ruta_foto',
        'id_categoria',
        'id_user',
        'calificacion',            

    ];

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'id_user');
    }
    public function categoria()
    {
        return $this->belongsTo('App\Models\categoria', 'id_categoria');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use  App\Models\Foto;
use  App\Models\Categoria;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $fotos = Foto::all()->where('id_user', Auth::user()->id);
        return view('home', compact('fotos'));
    }
}

app/Http/Controllers/categoria/CategoriaController.php
<?php

namespace App\Http\Controllers\categoria;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class CategoriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    
}

app/Http/Controllers/foto/FotoController.php
<?php

namespace App\Http\Controllers\foto;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use  App\Models\Categoria;
use  App\Models\Foto;
use  App\Models\User;
use Illuminate\Support\Facades\Auth;
use \Storage;


class FotoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $fotos = Foto::all();
        return view('inicio', compact('fotos'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categorias = Categoria::all();

        return view('fotos.create', compact('categorias'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input = $request->all();

        $path = Storage::disk('public')->putFile('imagenes', $request->file('ruta_foto'));

        $input['id_user'] = Auth::user()->id;
        $input['ruta_foto'] = str_ireplace('imagenes/','',$path);
        

        Foto::create($input);
        return redirect()->route('home')->with('status','Foto Publicada');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $foto = Foto::find($id);
        $categorias = Categoria::all();
        return view('fotos.edit', compact('foto','categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $input = $request->all();
        $foto = Foto::find($id);
        $foto->update($input);
        return redirect()->route('home')->with('status', 'Se ha modificado la foto');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $fotos = Foto::find($id);
        $fotos->delete();
        return redirect()->route('home')->with('status', 'Foto Eliminada');
    }

    public function perfilpublico($id_user)
    {
        $fotos= Foto::all()->where('id_user', $id_user); 
        return view('perfilpublico', compact('fotos'));
    }
}

resources/views/fotos/create.blade.php
@extends('layouts.layoutmain')

@section('contenido')


<div class="container">
    <section class="section">
        <h2 class="title is-8 has-text-link"> HOLA {{ Auth::user()->nickname }} SUBE TUS FOTOS</h2>
    
    </section>
    
        <div class="formulario">
        <form enctype="multipart/form-data" action="{{route('foto.store')}}" method="post">
            @csrf
            <div class="field">
                <div class="control">
                <input type="file" class="input is-link" accept="image/*" name="ruta_foto" required>
                </div>    
            </div>  
            <div class="mb-2">              
             
                <textarea placeholder="Algo que decir??" class="textarea is-link" name="descripcion"></textarea>
                
            </div>
            
            <div class="field">
                <div class="select is-link">
                   
                    <select name="id_categoria" class="input" >
                        
                        @foreach ($categorias as $categoria)
                        <option value="{{$categoria->id}}"> {{$categoria->nombre_categoria}}</option>
                        @endforeach   
        
                    </select>           
                </div>
            </div>
            <div class="field">
                <div class="select is-link">                    
                    <select name="calificacion" class="input">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>            
                </div>
            </div>
           
            <button class="button is-link" type="submit" > Publicar Foto</button>
        </form>
    </div>
</div> 
</div>



@endsection

resources/views/fotos/edit.blade.php
@extends('layouts.layoutmain')
@section('contenido')
        
    <section id="containereditar">
                  
        <article class="card">

           
            <form enctype="multipart/form-data" action="{{route('foto.update', $foto->id)}}" method="post">
                @csrf
                @method('PATCH')
                <img src="/storage/imagenes/{{$foto->ruta_foto}}" alt="">
                <div class="mb-2">
                    <textarea class="textarea is-link" placeholder="{{$foto->descripcion}}"  name="descripcion"></textarea>
                </div>
                
              
                <div class="select is-link">
                    <select  class="input" name="id_categoria" value="{{$foto->id_categoria}}" >
                        <option value="{{$foto->id_categoria}}"> {{$foto->categoria->nombre_categoria}}</option>
                        @foreach ($categorias as $categoria)
                        <option value="{{$categoria->id}}"> {{$categoria->nombre_categoria}}</option>
                        @endforeach   
        
                    </select>   
                </div>
                <div class="field mt-2 mb-2">
                    <div class="select is-link">                    
                        <select name="calificacion" class="input">
                            <option selected> {{$foto->calificacion}}</option>    
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>            
                    </div>
                </div>
                 <div class="field">
                    <div class="control">
                        <button class=" button is-link is-fullwidth" type="submit" > Editar </button>
                    </div>
                 </div>       
            </form>
        </article>
    </section>
@endsection

resources/views/home.blade.php
@extends('layouts.layoutmain')

@section('contenido')
<section class="section">
    
                <div class="section">
                        <h2 class="title is-2 is-spaced has-text-link">
                            <i class="fas fa-portrait fa-lg"></i> {{ Auth::user()->nickname }} !
                        </h2>                     
                </div>

                <div class="section-small">
                    @if (session('status'))
                        <div class="notification is-primary" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                  
                </div>
</section>
    <section class="container-fluid">
        <div class="columns is-multiline is-centered">
            

            
            @foreach ($fotos as $foto)
            <div class="column">
            <article class="card"> 
                <div class="card-img">                
                    <figure class="image" id="foto">
                        <img src="/storage/imagenes/{{$foto->ruta_foto}}" alt="">
                    </figure>
                </div>
                <div class="card-content">
                       
                    <div class="content">
                        <div id="contenedordescripcion">
                            <p> {{$foto->descripcion}}</p>
                        </div>
                        <div id="usuario">
                            <p class="title is-5"><a class="has-text-primary" href="{{route('perfilpublico', $foto->id_user)}}">
                            @ {{$foto->user->nickname}}
                          </a></p>
                        </div>
                        <div id="categorias">
                            <p class="tag is-warning">#{{$foto->categoria->nombre_categoria}}</p>
                          </div>
                          <p>{{$foto->calificacion}}</p>
                    <div id="botonescard">
                          <form action="{{route('foto.destroy', $foto->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="button is-link" type="submit">
                            <i class="fas fa-trash-alt fa-lg" >                            
                            </i>
                            </button>
                        </form>
                        
                        <a class="button is-link" href="{{route('foto.edit', $foto->id)}}"><i class="fas fa-edit fa-lg"></i></a>
                    </div>    
                    </div>
                </div>
            </article>
              
                
               
               
               
              
        </div>
            @endforeach
        </div>
        </div>
    </section>
 
        

@endsection

resources/views/inicio.blade.php
@extends('layouts.layoutmain')

@section('contenido')
    
<section>
    <div class="section is-medium">
            <h1 class="title is-1 is-spaced has-text-link"> HOLA, BIENVENIDOS A FOTOAPP</h1>
    </div>
</section>
<section class="container-fluid">
    <div  id="contenedor">
      <div id="tarjetas">

      
        @foreach ($fotos as $foto)
      
        <article class="card">
          <div class="card-img">
            <figure class="image" id="foto">
            <img src="/storage/imagenes/{{$foto->ruta_foto}}" alt="">
            </figure>
          </div>
          <div class="card-content">
                       
            <div class="content">
                <div id="contenedordescripcion">
                    <p>{{$foto->descripcion}}</p>
                </div>
                <div id="usuario">
                    <p class="title is-5"><a class="has-text-primary" href="{{route('perfilpublico', $foto->id_user)}}">
                    @ {{$foto->user->nickname}}
                  </a></p>
                </div>
                <div id="categorias">
                  <p class="tag is-warning">#{{$foto->categoria->nombre_categoria}}</p>
                </div>
                  <p>{{$foto->calificacion}}</p>
             </div>            
        </div>                     
        </article> 
      
        @endforeach   
      </div>
   </div>
</section>



@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->nickname }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/layoutmain.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/css/bulma/bulma.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>FotoApp</title>
</head>
<body>  
    
    <header>
        <nav>
            <ul class="navbar is-link">
                <!-- Authentication Links -->
                <li class="navbar-item">
                    <div class="buttons">
                        <a class="button is-success" href="/"> <i class="fas fa-home fa-lg"></i></a>
                    </div>
                    
                </li>
          <div class="navbar-end">
            <div class="navbar-item">
                @guest
                    @if (Route::has('login'))

                        <li class="navbar-item ">
                            <div class="buttons">
                            <a class="button is-primary is-light" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </div>
                        </li>
                    @endif

                    @if (Route::has('register'))
                        <li class="navbar-item">
                            <div class="buttons">
                            <a class="button is-primary is-light"  href="{{ route('register') }}">{{ __('Register') }}</a>
                            </div>    
                        </li>
                    @endif
                @else
                <li class="navbar-item">
                    <div class="buttons">
                    <a class="button is-primary is-light" href="{{route('foto.create')}}" role="button" >
                        <i class="fas fa-image fa-lg"></i>
                       
                    </a>
                    </div>
                </li>
                    <li class="navbar-item">
                        <div class="buttons">
                        <a class="button is-primary is-light" href="{{ route('home')}}"> <i class="fas fa-user fa-lg">  </i></a> 
                        </div>
                    </li>
                    <li class="navbar-item">
                        <div class="buttons">
                        <a class="button is-primary is-light" href="#" role="button" >
                            <i class="fas fa-cog fa-lg"></i>
                           
                        </a>
                        </div>
                    </li>
                    
                        <li class="navbar-item">
                            
                            <a class="button is-primary is-light" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout .') }} <i class="fas fa-sign-out-alt fa-lg"></i>
                            </a>
                            
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </li>                   
                @endguest
            </ul>
        </nav>
           

    </header>

    <section class="flex">
        @yield('contenido')   
       
    </section> 
    <footer class="footer">
        <h1> footer AQUI</h1>
    </footer>
    
      

</body>
</html>

resources/views/perfilpublico.blade.php
@extends('layouts.layoutmain')
@section('contenido')
            <section class="container-fluid">
                    <div class="columns is-multiline is-centered">

                           
                            @foreach ($fotos as $foto)
                            <div class="column">
                               <article class="card">
                                   <div class="card-img">
                                        <figure class="image" id="foto">
                                            <img src="/storage/imagenes/{{$foto->ruta_foto}}" alt="">
                                        </figure>
                                   </div>
                                   <div class="card-content">
                                        <div class="content">
                                            <div id="contenedordescripcion">
                                                <p>{{$foto->descripcion}}</p>
                                            </div>
                                            <div id="usuario">
                                                <p class="title is-5"><a class="has-text-primary" href="{{route('perfilpublico', $foto->id_user)}}">
                                                @ {{$foto->user->nickname}}
                                              </a></p>
                                            </div>
                                            <div id="categorias">
                                                <p class="tag is-warning">#{{$foto->categoria->nombre_categoria}}</p>
                                              </div>
                                              <p>{{$foto->calificacion}}</p>
                                        </div>
                                   </div>                              
                                </article>
                            </div>
                            @endforeach
                    </div>
            </section>
           

@endsection